# Status bar background and foreground colors
# set -g status-bg default   # Transparent background
# set -g status-fg colour130  # Soft grey for the status text

set -g xterm-keys on
set -g extended-keys on
set -ag terminal-features 'xterm*:extkeys'

set -g status off

# Active window title (left side)
# set -g status-left '#[fg=colour155,bg=default,bold] #S  '

# Display date, time, and battery info
# set -g status-right '#[fg=colour227,bg=default] #(if ip a | grep -q ppp0; then echo "🖧 vpn"; else echo "🖧 home"; fi) #[fg=colour155,bg=default] %Y-%m-%d #[fg=colour155,bg=default] %H:%M:%S #[fg=colour227,bg=default] #(acpi -b | awk "{gsub(\"%\", \"\", \$4); if (\$4 < 80) {print \$4} fi}")'

# Pane border colors
# set -g pane-active-border-style 'fg=colour155'  # Bright yellow for active pane
# set -g pane-border-style 'fg=colour245'         # Very light grey for inactive panes
#
# # Window titles
# set -g window-status-current-style 'fg=colour227,bg=default'  # Bright red text for the active window
# set -g window-status-style 'fg=colour245,bg=default'    # Light grey text for inactive windows
#
# # Status bar style and separator
# set -g status-style 'bg=default,fg=colour130'
# set -g status-left-length 60
# set -g status-right-length 100

# Other settings
# set -g message-style 'bg=colour155,fg=black'  # Message background yellow, text black
# set -g display-panes-active-colour 'colour155'  # Bright yellow for the active pane display
# set -g display-panes-colour 'colour245'         # Light grey for inactive panes

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind r source-file ~/.tmux.conf

set -g base-index 1
set-option -g history-limit 100000

# ================================

#==Sensible==============================
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 5

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

bind c new-window -c '#{pane_current_path}'

#==Sensible==============================
