#!/usr/bin/env bash

set -euo pipefail

PASSWORD_FILE="password.txt"

FILES_TO_ENCRYPT=($(find secrets/ -type f))

echo "=== ENCRYPTION =========================="

ansible-vault encrypt --vault-password-file "${PASSWORD_FILE}" -- "${FILES_TO_ENCRYPT[@]}"

git add "${FILES_TO_ENCRYPT[@]}"

echo -e "\n"
