---
######################
# ssh
######################

- name: Ensure .ssh directory exists.
  file:
    dest: "~/.ssh"
    mode: 0700
    state: directory

- name: Find all private ssh keys
  find:
    paths: "{{ playbook_dir }}/secrets/ssh"
    patterns: "*[^.]*"
  register: ssh_keys_files

- name: Decrypt each private ssh key
  command: ansible-vault decrypt {{ ssh_key_file.path }}
  loop: "{{ ssh_keys_files.files }}"
  loop_control:
    loop_var: ssh_key_file
  ignore_errors: true

- name: Copy all the ssh keys to ~/.ssh folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/secrets/ssh"
    dest: "/home/{{ user }}/.ssh/"
    mode: "0600"
#
######################
# passwords store
######################

- name: Find all the password files
  find:
    paths: "{{ playbook_dir }}/secrets/passwords"
    patterns: "*.*"
  register: password_files

- name: Decrypt each password file
  command: ansible-vault decrypt {{ pass_file.path }}
  loop: "{{ password_files.files }}"
  loop_control:
    loop_var: pass_file
  ignore_errors: true
