---
- name: Ensure .ssh directory exists.
  file:
    dest: "~/.ssh"
    mode: 0700
    state: directory

# SSH

- name: Find all secret files without extensions
  find:
    paths: "{{ playbook_dir }}/secrets/index"
    patterns: "*[^.]*"
  register: secret_files

- name: Decrypt each secret file
  command: ansible-vault decrypt {{ secret_file.path }}
  loop: "{{ secret_files.files }}"
  loop_control:
    loop_var: secret_file
  ignore_errors: true

- name: Copy all decrypted files to .ssh folder
  ansible.builtin.copy:
    src: "{{ secret_file_dec.path }}"
    dest: "/home/{{ user }}/.ssh/"
    mode: "0600"
  loop: "{{ secret_files.files }}"
  loop_control:
    loop_var: secret_file_dec
    #
# passwords
