---
- name: Find Google Chrome desktop file
  find:
    paths: /usr/share/applications
    patterns: "google-chrome.desktop"
  register: chrome_desktop_file
  become: true

- name: Ensure Google Chrome desktop file is found
  fail:
    msg: "Google Chrome desktop file not found."
  when: chrome_desktop_file.matched == 0

- name: Update all Exec lines in Google Chrome desktop file
  replace:
    path: "{{ google_chrome_desktop_file.path }}"
    regexp: "^Exec=.*"
    replace: "Exec=/usr/bin/google-chrome-stable --force-device-scale-factor=2 --start-fullscreen %U"
    backup: yes
  loop: "{{ chrome_desktop_file.files }}"
  loop_control:
    loop_var: google_chrome_desktop_file
  when: chrome_desktop_file.matched > 0
  become: true

- name: Notify user of changes
  debug:
    msg: "Google Chrome desktop file updated to set scale factor to 2."
