---
- name: Set zsh as default shell
  shell: chsh -s $(which zsh) "{{ user }}"
  become: true

# ------------------------------
# main setup
# ------------------------------

- name: Check if Oh My Zsh is installed
  stat:
    path: /home/{{ user }}/.oh-my-zsh
  register: oh_my_zsh_installed

- name: Remove previous omz cfg
  file:
    path: /home/{{ user }}/.oh-my-zsh
    state: absent
  become: true
  when: oh_my_zsh_installed.stat.exists

- name: Install oh-my-zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/zsh
  when: not oh_my_zsh_installed.stat.exists

# ------------------------------
# omz plugins
# ------------------------------

- name: Define plugins
  set_fact:
    omz_plugins:
      - name: zsh-syntax-highlighting
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      - name: zsh-autosuggestions
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
      - name: you-should-use
        repo: https://github.com/MichaelAquilina/zsh-you-should-use.git

- name: Install plugins
  git:
    repo: "{{ omz_pl.repo }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ omz_pl.name }}"
    update: true
    depth: 1
  loop: "{{ omz_plugins }}"
  loop_control:
    loop_var: omz_pl
