- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
  vars:
    user: bohdan
    plugins:
      - name: zsh-syntax-highlighting
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      - name: zsh-autosuggestions
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      - name: you-should-use
        repo: 'https://github.com/MichaelAquilina/zsh-you-should-use.git'
    aliases:
      - 'alias dev="npm run dev"'
      - 'alias build="npm run build"'
      - 'alias start="npm run start"'
      - 'alias gpilot="gh copilot"'
      - 'alias ghs="ghs copilot suggest"'
      - 'alias ghe="ghe copilot explain"'
      - 'alias open="xdg-open"'
    packages:
      - name: nodejs
      - name: npm
  tasks:
    - name: Install packages
      apt:
        name: "{{ item.name }}"
        state: present
      become: yes
      loop: "{{ packages }}"

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ user }}"

    - name: Set zsh as default shell
      shell: chsh -s $(which zsh) "{{ user }}"
      become: yes

    - name: Install plugins
      git:
        repo: "{{ item.repo }}"
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
      become: yes
      become_user: "{{ user }}"
      loop: "{{ plugins }}"

    - name: Configure .zshrc
      block:
        - name: Source oh-my-zsh.sh in .zshrc
          lineinfile:
            path: "/home/{{ user }}/.zshrc"
            line: 'source $HOME/.oh-my-zsh/oh-my-zsh.sh'
            insertbefore: 'BOF'
          become: yes
          become_user: "{{ user }}"

        - name: Enable plugins in .zshrc
          lineinfile:
            path: "/home/{{ user }}/.zshrc"
            regexp: '^plugins='
            line: "plugins=(git {{ plugins | map(attribute='name') | join(' ') }})"
          become: yes
          become_user: "{{ user }}"

        - name: Add aliases to .zshrc
          lineinfile:
            path: "/home/{{ user }}/.zshrc"
            line: "{{ item }}"
          loop: "{{ aliases }}"
          become: yes
          become_user: "{{ user }}"

        - name: Source nvm in .zshrc
          lineinfile:
            path: "/home/{{ user }}/.zshrc"
            line: 'export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
            insertbefore: 'BOF'
          become: yes
          become_user: "{{ user }}"

    - name: Install nvm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ user }}"

    - name: Apply changes to zshrc file
      shell: source ~/.zshrc
      args:
        executable: /bin/zsh
      become: yes
      become_user: "{{ user }}"
