##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

monitor = DP-1,preferred,auto,1
monitor = eDP-1,preferred,auto,1

# This is the critical part - it tells Hyprland to use eDP-1 when no other monitors are available
monitor = ,preferred,auto,1

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1, default:true
workspace = 3, monitor:DP-1, default:true
workspace = 4, monitor:DP-1, default:true
workspace = 5, monitor:DP-1, default:true
workspace = 6, monitor:DP-1, default:true
workspace = 7, monitor:DP-1, default:true
workspace = 8, monitor:DP-1, default:true
workspace = 9, monitor:DP-1, default:true
workspace = 10, monitor:DP-1, default:true

#

# # Default layout
# layout=default,tiling
# #!/bin/bash
# # Get external monitor name (adjust as needed)
# EXTERNAL=$(hyprctl monitors -j | jq -r '.[] | select(.name != "eDP-1") | .name')
# # Move workspaces from laptop to external monitor
# for WORKSPACE in $(hyprctl workspaces -j | jq -r '.[] | select(.monitor == "eDP-1") | .id'); do
#   hyprctl dispatch moveworkspacetomonitor "$WORKSPACE" "$EXTERNAL"
# done
