FROM ubuntu:26.04

COPY .gnupg/private-keys-v1.d/3F8B20FBE0ED2DC0ECD533D56661CE64D7E8A8F2.key /root/.gnupg/private-keys-v1.d/
COPY .gnupg/private-keys-v1.d/FA5DE4470687D6D2ABBB530C4E56172E13A38854.key /root/.gnupg/private-keys-v1.d/
COPY .gnupg/devcon-public.asc /root/.gnupg/
