---
- name: Find all files in ./config
  find:
    paths: "{{ playbook_dir }}/packages/config"
    patterns: "*.yml"
  register: pckg_config_files

- name: Include each config file
  include_tasks: "{{ pckg_config_file.path }}"
  loop: "{{ pckg_config_files.files }}"
  loop_control:
    loop_var: pckg_config_file
