ids]
*
[main]
capslock = leftcontrol
rightalt = esc
leftalt= layer(f_layer)

[f_layer:C]
k = up
h = left
j = down
l = right
u = home
o = end

capslock = backspace

v = macro(S-enter ``` S-enter C-v S-enter ``` )
