[ids]
*
[main]
capslock = backspace
leftalt= layer(f_layer)
rightalt= layer(s_layer)

[f_layer:C]
k = up
h = left
j = down
l = right
u = home
o = end
grave = macro(C-c ` C-v `)

[s_layer:C]
grave = macro(```)
