---
######################
# ssh
######################

- name: Ensure .ssh directory exists.
  file:
    dest: "~/.ssh"
    mode: 0700
    state: directory

- name: Decrypt each private SSH key
  command: ansible-vault decrypt {{ item }} --output "/home/{{ user }}/.ssh/{{ item | basename }}"
  with_fileglob:
    - "{{ playbook_dir }}/secrets/ssh/*"
  when: item.split('.')[-1] != 'pub'
  ignore_errors: true

- name: Copy all the public ssh keys to ~/.ssh folder
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.ssh/{{ item | basename }}"
    mode: "0644"
  with_fileglob:
    - "{{ playbook_dir }}/secrets/ssh/*.pub"

- name: Ensure only the user have access to .ssh files
  file:
    path: "{{ item }}"
    mode: "0600"
  with_fileglob:
    - "~/.ssh/*"

#
######################
# passwords store
######################

- name: Create secrets folder
  file:
    path: "/home/{{ user }}/secrets"
    state: directory
    mode: "0600"
  register: secrets_dir_result

- name: Decrypt each password file
  command: ansible-vault decrypt {{ item }} --output {{ secrets_dir_result.path }}/{{ item | basename }}
  with_fileglob:
    - "{{ playbook_dir }}/secrets/passwords*"
  ignore_errors: true
#
######################
# vpn credentials
######################

- name: Decrypt vpn credentials file
  command: ansible-vault decrypt {{ playbook_dir }}/secrets/vpn/credentials.cfg  --output {{ secrets_dir_result.path  }}/vpn_credentials.cfg
  ignore_errors: true
