# kitty.conf

# == audio ===============
enable_audio_bell no
window_alert_on_bell no

# == looks ===============
font_size 14
font_family Fira Code 'Font Awesome' 'MesloLGS NF'
background_opacity 1.0
hide_window_decorations yes

# == behaviour ===============
confirm_os_window_close 0
clipboard_control write-primary write-clipboard no-append
