# kitty.conf

font_family Fira Code 'Font Awesome' 'MesloLGS NF'

# Disable bell sound
enable_audio_bell no

# Disable bell in the terminal
window_alert_on_bell no

font_size 14.0

background_opacity 0.8

hide_window_decorations yes
