---
- name: Define package list
  set_fact:
    packages:
      - "git"
      - "base-devel"
      - "keepassxc"
      - "aws-cli-v2"
      - "bruno"
      - "docker-desktop"
      - "grimshot"
      - "members"
      - "ttf-ms-fonts"
      - "xwaylandvideobridge-git"
      - "yay"
      - "tmux"
      - "neovim"
      - "openfortivpn"
      - "fzf"
      - "github-cli"
      - "zsh"

- name: Install necessary packages for Arch
  pacman:
    name: "{{ packages }}"
    state: present
# - name: Define aur package list
#   set_fact:
#     packages:
#       - "git"
#       - "google-chrome-stable"
# - name: Install necessary packages for Arch using yay
#   become: yes
#   shell: yay -S --noconfirm {{ item }}
#   loop: "{{ packages }}"
#   args:
#     executable: /bin/zsh
