---
# ------------------------------
# pacman
# ------------------------------

- name: Define package list
  set_fact:
    pacman_packages:
      - "git"
      - "base-devel"
      - "keepassxc"
      - "aws-cli-v2"
      - "bruno"
      - "docker-desktop"
      - "grimshot"
      - "members"
      - "ttf-ms-fonts"
      - "xwaylandvideobridge-git"
      - "yay"
      - "tmux"
      - "neovim"
      - "openfortivpn"
      - "fzf"
      - "github-cli"
      - "zsh"
      - "fzf"

- name: Install necessary packages for Arch
  pacman:
    name: "{{ pacman_packages }}"
    state: present

# ------------------------------
# yay
# ------------------------------

# install yay itself
- name: Check if yay is already installed
  stat:
    path: /usr/bin/yay
  register: yay_installed

- name: Clone yay-git repository
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/tmp/yay-git"
  when: not yay_installed.stat.exists

- name: Build and install yay
  command:
    cmd: makepkg -sri
    chdir: /tmp/yay-git
    creates: /usr/bin/yay
  when: not yay_installed.stat.exists

# install packages using yay
- name: Define aur package list
  set_fact:
    yay_packages:
      - "google-chrome-stable"

- name: Install aur packages using yay
  become: true
  shell: yay -S --noconfirm {{ yay_package }}
  loop: "{{ yay_packages }}"
  loop_control:
    loop_var: yay_package
  args:
    executable: /bin/bash
