---
- name: Set zsh as default shell
  shell: chsh -s $(which zsh) "{{ user }}"
  become: true

# ------------------------------
# main setup
# ------------------------------

- name: Remove previous omz cfg
  file:
    path: /home/{{user}}/.oh-my-zsh
    state: absent
  become: true

- name: Install oh-my-zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/zsh

# ------------------------------
# omz plugins
# ------------------------------

- hosts: localhost
  tasks:
    - name: Define plugins
      set_fact:
        plugins:
          - name: git
            repo: https://github.com/zsh-users/git.git
          - name: docker
            repo: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/docker
          - name: zsh-syntax-highlighting
            repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
          - name: zsh-autosuggestions
            repo: https://github.com/zsh-users/zsh-autosuggestions.git
          - name: you-should-use
            repo: https://github.com/MichaelAquilina/zsh-you-should-use.git

- name: Install plugins
  git:
    repo: "{{ pl.repo }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ pl.name }}"
  loop: "{{ plugins }}"
  loop_control:
    loop_var: pl
