#!/usr/bin/env bash


utils=$(cat <<EOF
find
man
tldr
sed
awk
tr
cp
ls
grep
xargs
rg
ps
mv
kill
lsof
less
head
tail
tar
cp
rm
rename
jq
cat
ssh
cargo
git
git-worktree
git-status
git-commit
git-rebase
docker
docker-compose
stow
chmod
chown
make
EOF
)


languages=$(cat <<EOF
golang
solidity
vlang
v
nodejs
javascript
tmux
typescript
zsh
cpp
c
lua
rust
python
bash
php
haskell
ArnoldC
css
html
gdb
EOF
)

function printDelimeter() {
  echo -e "------------------------------------------------ $*"
}


while :; do
  selected=$(echo -e "$languages\n$utils" | fzf)

  if [[ -z $selected ]]; then
      exit 0
  fi

  echo 'Selected:' "$selected"
  echo -n "Enter Query: "
  read -r query

  printDelimeter

  if grep -qs "$selected" <<< "$languages"; then
      echo "cht.sh/$selected/$query"
      printDelimeter "\n"

      query=$(echo "$query" | tr ' ' '+')
      curl cht.sh/"$selected"/"$query" 
  else 
      echo "cht.sh/$selected~$query"
      printDelimeter

      curl cht.sh/"$selected"~"$query" 
  fi

  printDelimeter "\n\n"

  echo -n "Press Enter to continue quering cheat.sh..."
  read -r
done


