#!/usr/bin/env bash

utils=$(cat <<EOF
find
man
tldr
sed
awk
tr
cp
ls
grep
xargs
rg
ps
mv
kill
lsof
less
head
tail
tar
cp
rm
rename
jq
cat
ssh
cargo
git
git-worktree
git-status
git-commit
git-rebase
docker
docker-compose
stow
chmod
chown
make
EOF
)


languages=$(cat <<EOF
golang
solidity
vlang
v
nodejs
javascript
tmux
typescript
zsh
cpp
c
lua
rust
python
bash
php
haskell
ArnoldC
css
html
gdb
EOF
)


selected=$(echo -e "$languages\n$utils" | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

read -rp "Enter Query: " query

if grep -qs "$selected" <<< "$languages"; then

  query=`echo $query | tr ' ' '+'`
  tmux neww bash -c "echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done"
	# tmux split-window -h bash -c "curl -s -S cht.sh/$selected/$(echo "$query" | tr ' ' '+') | less"
else 
  tmux neww bash -c "echo \"curl cht.sh/$selected~$query/\" & curl cht.sh/$selected~$query & while [ : ]; do sleep 1; done"
fi

# learn:slice
# :learnslice
#
# cht.sh/lang/descri+of+operation
# cht.sh/something~operation

