#!/usr/bin/env bash

session=$(find ~ ~/dev ~/dev/ib ~/dev/my ~/dev/lw ~/pers/xdg -mindepth 1 -maxdepth 1 -type d ! -name '.*' | fzf --height=~25 --border --delimiter='/' --with-nth='4..' --prompt="Workdir?: ")

[ -z "$session" ] && exit 0

if ! tmux ls &>/dev/null; then
  tmux start-server
fi

session_name=$(echo "$session" | tr './' '_')
if ! tmux has-session -t "$session_name" 2>/dev/null; then

  LOCAL_DC_DIR="$session/.devcontainer"
  GLOBAL_DC_CONFIG="$HOME/pers/.devcontainer/devcontainer.json"

  if [ -d "$LOCAL_DC_DIR" ]; then
    tmux new-session -s "$session_name" -c "$session" -d
    tmux send-keys -t "$session_name" "devcon up --workspace-folder . --remove-existing-container" C-m
    tmux send-keys -t "$session_name" "devcon exec --workspace-folder . 'nvim' '--cmd' 'lua vim.g.sessionizer_devcon = true'" C-m

  elif [ -f "$GLOBAL_DC_CONFIG" ]; then
    tmux new-session -s "$session_name" -c "$session" -d
    tmux send-keys -t "$session_name" "devcon up --workspace-folder . --config $GLOBAL_DC_CONFIG --remove-existing-container" C-m
    tmux send-keys -t "$session_name" "devcon exec --workspace-folder . --config $GLOBAL_DC_CONFIG 'nvim' '--cmd' 'lua vim.g.sessionizer_devcon = true'" C-m

  else
    tmux new-session -s "$session_name" -c "$session" -d "nvim --cmd lua vim.g.sessionizer_devcon = true"
  fi
fi

if [ -z "$TMUX" ]; then
  exec tmux attach-session -t "$session_name"
else
  tmux switch-client -t "$session_name"
fi

