#!/usr/bin/env bash
# shellcheck disable=SC2155

# The server name of the calling nvim instance is passed as the first argument
NVIM_SERVER=$1

main() {
  session=$(find ~ ~/dev -mindepth 1 -maxdepth 1 -type d ! -name '.*' |
    fzf --height=80% --margin=25% --border=rounded \
      --prompt="Workdir?: " --delimiter='/' --with-nth='4..')
  [ -z "$session" ] && return 0

  local tmux_session_name=$(basename "$session" | tr '.' '_')

  if [ -n "$TMUX" ]; then
    current_session_name=$(tmux display-message -p '#S')
    if [ "$current_session_name" == "$tmux_session_name" ]; then
      exit 0 # Do nothing if selecting the current session
    fi
  fi

  if ! tmux ls &>/dev/null; then
    tmux start-server
  fi

  if ! tmux has-session -t "$tmux_session_name" 2>/dev/null; then
    tmux new-session -s "$tmux_session_name" -c "$session" -d
    tmux send-keys -t "$tmux_session_name" "SESSIONIZER_START=true nvim" C-m
  fi

  if [ -z "$TMUX" ]; then
    tmux attach-session -t "$tmux_session_name"
  else
    if [ -n "$NVIM_SERVER" ]; then
      # 2. Tell the original Neovim to quit cleanly.
      # --server specifies the target instance.
      # --remote-send sends keystrokes. We send Escape, then :qa, then Enter.
      nvim --server "$NVIM_SERVER" --remote-send '<Esc>:q<CR>'
    fi
    tmux switch-client -t "$tmux_session_name"
  fi
}

main "$@"


  # is_bare=$(git rev-parse --is-bare-repository 2>/dev/null)
  #
  # if [ "$is_bare" = "true" ]; then
  #   source "$HOME/pers/scripts/create_worktree"
  #
  #   worktree=$(git worktree list --porcelain 2>/dev/null | awk '/worktree /{print $2}' | tail -n1)
  #   if [ -n "$worktree" ]; then
  #     cd "$worktree" || return 1
  #   else
  #     echo "Failed to locate a valid worktree."
  #     return 1
  #   fi
  # fi
