#!/usr/bin/env bash

# Find the directory to work with
session=$(find ~ ~/dev -mindepth 1 -maxdepth 1 -type d ! -name '.*' | fzf --height=25 --border --delimiter='/' --with-nth='4..' --prompt="Workdir?: ")
session_name=$(basename "$session" | tr . _)

# Check if the tmux server is running
if ! tmux ls &>/dev/null; then
  tmux start-server
fi

# Check if the session exists
if ! tmux has-session -t "$session_name" 2>/dev/null; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

# Attach to the tmux session or switch to it
if [ -z "$TMUX" ]; then
  tmux attach-session -t "$session_name"
else
  tmux switch-client -t "$session_name"
fi
