#!/usr/bin/env bash

trees=$(git worktree list --porcelain | grep -i "worktree" | sed '1d' | awk '{print $2}')
echo "${trees[@]}"

tree=$(echo "${trees[@]}" | fzf --height=15 --border --delimiter='/' --with-nth='4..')
cd "${tree}" || exit
