- name: Clone keyd repository
  git:
    repo: 'https://github.com/rvaiya/keyd.git'
    dest: '/tmp/keyd'
    clone: yes
    update: yes

- name: Build and install keyd
  command: '{{ command_name }}'
  args:
    chdir: '/tmp/keyd'
  loop:
    - 'make'
    - 'sudo make install'
  loop_control:
    loop_var: command_name

- name: Enable and start keyd service
  systemd:
    name: keyd
    enabled: yes
    state: started

- name: Create keyd config directory
  file:
    path: '/etc/keyd'
    state: directory
    mode: '0755'

- name: Change owner of keyd config directory
  file:
    path: '/etc/keyd'
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
  become: true

- name: Write keyd config
  copy:
    content: |
      [ids]
      *
      [main]
      capslock = backspace
      rightalt = layer(movement_layer)
      [movement_layer:C]
      i = up
      j = left
      k = down
      l = right
      u = home
      o = end
    dest: '/etc/keyd/default.conf'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'

- name: Restart keyd service
  systemd:
    name: keyd
    state: restarted
  become: true
