- hosts: localhost
  gather_facts: true
  become: false
  pre_tasks:
    - name: Initial setup
      include_tasks: setup.yml
  vars:
    user: "{{ ansible_env.USER }}"
  tasks:
    - name: Include tasks
      include_tasks: "{{ item }}.yml"
      loop:
        - packages/install
        - packages/config
        # - keyd
        # - node
        # - secrets
        # - dotfiles
