- hosts: localhost
  gather_facts: no
  become: false
  pre_tasks:
    - name: Initial setup
      include_tasks: setup.yml
  vars:
    user: 'bchk'
  tasks:
    - name: Include tasks
      include_tasks: '{{ item }}.yml'
      loop:
        - packages
        - zsh
        - aliases
        - git
        - keyd
        - node
        - secrets
#
#
# ansible-pull -U https://github.com/bbuukk/pers.git ansible/main.yml
# install rvm and ruby
# install google chrome dev and change its 
# sudo vim /usr/share/applications/google-chrome.desktop
#Exec=/usr/bin/google-chrome-stable --force-device-scale-factor=2 %U
# to have scale factor
#
# install tmux 
# install fzf https://github.com/junegunn/fzf?tab=readme-ov-file#installation and ./install it 
#
#
# screate script to fzf into tmux sessions

# install tmux 
# 

# change config of pacman
# uncomment color and parallel downloads, also add line ILoveCandy, then update the pacman by writing pacman -Sy

# install mercurial dvs, and then install firefox-nightly