- name: Define package list
  set_fact:
    packages:
      - "git"
      - "base-devel"
      - "keepassxc"
      - "aws-cli-v2"
      - "bruno"
      - "docker-desktop"
      - "google-chrome"
      - "grimshot"
      - "members"
      - "ttf-ms-fonts"
      - "xwaylandvideobridge-git"
      - "yay"
      - "tmux"
      - "neovim"
      - "openfortivpn"

- name: Install necessary packages for Arch
  pacman:
    name: "{{ packages }}"
    state: present

    sioyek to install!
