# - name: Define variables
#   set_fact:
#     plugins:
#       - name: zsh-syntax-highlighting
#         repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
#       - name: zsh-autosuggestions
#         repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
#       - name: you-should-use
#         repo: 'https://github.com/MichaelAquilina/zsh-you-should-use.git'

# local.yml
  ...
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  ...

# ssh file
- name: Ensure .ssh directory exists.
  become_user: root
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install ssh key
  become_user: root
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tags:
    - dotfiles
    - ssh

# clone down the dotfiles and recurse the submodules (which are private)
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:ThePrimeagen/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles

ansible-playbook -t dotfiles local.yml --ask-become-pass --ask-vault-pass