#SSH
- name: Ensure .ssh directory exists.
  file:
    dest: '~/.ssh'
    mode: 0700
    state: directory

- name: Decrypt shh private keys
  command: ansible-vault decrypt {{ key_file }}
  loop:
    - ~/pers/ssh/id_ed25519
    - ~/pers/ssh/id_rsa
  loop_control:
    loop_var: key_file
  ignore_errors: true

- name: Install ssh key
  ansible.builtin.copy:
    src: '/home/{{user}}/pers/ssh/'
    dest: '/home/{{user}}/.ssh'
    mode: 0600
  # become: true

# does not work somewhy
# fatal: [localhost]: FAILED! => {"changed": false, "msg": "invalid key specified: ~/.ssh/id_rsa.pub"}
# - name: Set authorized key took from file
#   authorized_key:
#     user: '{{ user }}'
#     state: present
#     key: '~/.ssh/id_rsa.pub'

# DOTFILES

# # clone down the dotfiles and recurse the submodules (which are private)
# - name: Cloning .dotfiles
#   ansible.builtin.git:
#     repo: 'git@github.com:ThePrimeagen/.dotfiles.git'
#     dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
#     recursive: yes
#     update: yes
#     accept_hostkey: yes
#     version: master

#KEEPASSXC

- name: Decrypt the file
  command: ansible-vault decrypt ~/pers/keepassxc/key_encrypted --output=~/pers/keepassxc/key_decrypted 
  ignore_errors: true
 