- name: Update cache (Arch)
  become: true
  pacman:
    update_cache: yes

- name: Install Python for Ansible on Arch
  raw: test -e /usr/bin/python || (pacman -Sy --noconfirm python)

- name: Clone yay-git repsitory
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/tmp/yay-git"
  when: ansible_os_family == "Archlinux"

- name: Build and install yay
  command:
    cmd: makepkg -sri
    chdir: /tmp/yay-git
    creates: /usr/bin/yay
  when: ansible_os_family == "Archlinux"
