- name: Update cache (Arch)
  become: true
  pacman:
    update_cache: yes

- name: Copy pacman.conf to /etc
  copy:
    src: "{{ playbook_dir }}/cfg/pacman.conf"
    dest: "/etc/pacman.conf"
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Install Python for Ansible on Arch
  raw: test -e /usr/bin/python || (pacman -Sy --noconfirm python)

- name: Clone yay-git repsitory
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/tmp/yay-git"

- name: Build and install yay
  command:
    cmd: makepkg -sri
    chdir: /tmp/yay-git
    creates: /usr/bin/yay
