# Update cache and install Python for Ansible
#   Debian OS family
- name: Update cache (Debian)
  apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install Python for Ansible on Debian
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  when: ansible_os_family == "Debian"

#   Archlinux OS
- name: Update cache (Arch)
  pacman:
    update_cache: yes
  when: ansible_os_family == "Archlinux"

- name: Install Python for Ansible on Arch
  raw: test -e /usr/bin/python || (pacman -Sy --noconfirm python)
  when: ansible_os_family == "Archlinux"

- name: Clone yay-git repository
  git:
    repo: 'https://aur.archlinux.org/yay-git.git'
    dest: '/tmp/yay-git'
  when: ansible_os_family == "Archlinux"

- name: Build and install yay
  command:
    cmd: makepkg -sri
    chdir: /tmp/yay-git
    creates: /usr/bin/yay
  when: ansible_os_family == "Archlinux"
