- name: Install Python for Ansible on Ubuntu
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  become: yes
  gather_facts: no
  when: ansible_os_family == "Debian"

- name: Install Python for Ansible on Arch
  raw: test -e /usr/bin/python || (pacman -Sy --noconfirm python)
  become: yes
  gather_facts: no
  when: ansible_os_family == "Archlinux"
