- name: Define variables
  set_fact:
    plugins:
      - name: zsh-syntax-highlighting
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      - name: zsh-autosuggestions
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      - name: you-should-use
        repo: 'https://github.com/MichaelAquilina/zsh-you-should-use.git'

- name: Install zsh
  pacman:
    name: zsh
    state: present

- name: Remove previous cfg
  file:
    path: /home/{{user}}/.oh-my-zsh
    state: absent
  become: true


- name: Install oh-my-zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/zsh
    
- name: Set zsh as default shell
  shell: chsh -s $(which zsh) "{{ user }}"
  become: true

- name: Install plugins
  git:
    repo: '{{ pl.repo }}'
    dest: '~/.oh-my-zsh/custom/plugins/{{ pl.name }}'
  loop: '{{ plugins }}'
  loop_control:
    loop_var: pl

- name: Check if .zshrc exists
  stat:
    path: '~/.zshrc'
  register: zshrc

- name: Create .zshrc if it does not exist
  file:
    path: '~/.zshrc'
    state: touch
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'
  when: not zshrc.stat.exists

- name: Configure .zshrc
  block:
    - name: Source oh-my-zsh.sh in .zshrc
      lineinfile:
        path: '~/.zshrc'
        line: 'source $HOME/.oh-my-zsh/oh-my-zsh.sh'
        insertbefore: 'BOF'

    - name: Enable plugins in .zshrc
      lineinfile:
        path: '~/.zshrc'
        regexp: '^plugins='
        line: "plugins=(git {{ plugins | map(attribute='name') | join(' ') }})"

- name: Apply changes to zshrc file
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
