-----BEGIN PGP MESSAGE-----

hF4D7/9t5OpFi7oSAQdAJc7Io8HiicUPjYJSfLRmqN+Lf4qow/dbC+31YTt6EQYw
/VBGyFJH+WKWCnQLPm7hIL4ACJLRui8axm/epMgmowTWNmyU/bkYuxBFt6suiBuf
0ukBlS8rTLH6/fMvU7uEcB9BDPilmkSD5Dym/xM1YLqQJBtlJ/JQqKsnC4ZfYYLO
bu/JzBg4eTszymhCNBLLb2NHXxiGsLu44pMNcMi3ZvTS8QHCF46CgLy16cj3ZmKJ
ioapIDN/l6+/uOtRv+XWaMEvIMPQr72ER1sfo79+GN2PLu+A6cEsF0AieoYbkLtG
SzP33MnoCkYi+Sxv0lvasN3P/ofRF/SEIXSZJbedqXru+c08HFVNsn0BmfQgfibp
J1FW8Kb7+k3ZNX8APolrgG0frFPYgbGVis0+qslsLP8GRj/rY8dbZXZJd1rVszdl
P53NM3zHzOGJi0gYJePDl4PkvNR7KqkwTcmP0v+26LcuR78ckSpdFQ7izUteLoDZ
gQjH9cKWP2ybn1g1OLbfjsChoxuYb3uxwI/8nEFRerXkxUPgLZGs7hixaa5Wma2c
Xp7bpI1bCrIi4t9hVAKnr6DOph2Lq+/MAP6z45QdxD3CL5qCniQtHfpVtH00l5iX
r4WE+LjIFBOOJXg7O5Iie/kEpYbPOdb14L3Y1/c0Cw8T/55ndBd2G7t/UgAAKHKB
EjMQo+Y5sknhp5Fq/Rk0C+eEBjby8TOChfr0fxiz/+6UzOI+o9dCX4cQ+OXoD22K
by06KUuZyQJx/PyUO4FG67It1Y28eixXWsuMVk7cG+Wag8EvIMSYfbfZDutLUJuA
2l8qR2/PQtLVKFqnOBCp1dRysqaJuveJzp+O495oQdN3Gq7aBxLaN7nZjSBZV3fb
2HtVAv3z4oLumZZcQ4vGbAGVZZtbcb9rwjzq/EkBNmyDLQir2AMRlxcy+OjwQt62
7G6qZFHPBqTKEoZKWV7rxMC8xB3B8U6YOYqqxJFX9mqkqzAEUP/laHaXoKJsnR6K
FX+Mpwl+rN28mIMAJ/GxgKh7s3AmwEYVqAjqRpzJ/AaqaolSI6p+4BWQzIxRWgTg
YwonY8thJVVu69wFdnbSNNL5mNxkiCNPv02uI9FSqgvOZE0UQzuKtNGTDzNBKqbO
BwT71rgdgVyRxSnBd5l58ttb2lrm46KtPRV3RaM4Xt8UKqzhu15WRr/SDUM5MMba
y7KGQ84ppsbzmGOtGpax9J2qN8nJenbqlO8linFnewE+Gd2/O2RyT9ViAKKu+2I8
kFx/y+LlX5PpuU7FK0J2DDRHUcZlRJMIRPiJ/xb6CGPbetUmBnUfptir6tFH98gh
fVfnM6ORugVebHSOXrkP0QChC4bCFQ4vjD03nSee2Ek/DRtz699gTeTMuzLGCVYd
8u9FXp/mh9gPC/sTbU+n70oZYIS+gTL/KR6KVvlbi3UL6HGc2dsErxS4Pk2nfF1s
C187
=usdI
-----END PGP MESSAGE-----
