#!/usr/bin/env bash

set -e

# cleanup() {
#     rm -rf "$WORK_DELETED_PATH"
# }
#
# trap cleanup ERR

url=$1
basename=${url##*/}
name=${2:-${basename%.*}}

mkdir -p "$name"
WORK_DELETED_PATH=$(readlink -f "$name")
cd "$WORK_DELETED_PATH"

git clone --bare "$url" .bare
echo "gitdir: ./.bare" >.git

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"

git fetch origin

most_active_branches=($(git for-each-ref --sort=-committerdate refs/remotes/origin/ --format='%(refname:short)' | sed 's/origin\///' | head -n 5))

for branch in "${most_active_branches[@]}"; do
  dir=$(echo "$branch" | tr '/' '_')
  git worktree add "$dir" "$branch"
done
