---
- name: Install fzf
  hosts: all
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
      become: yes

    - name: Clone fzf repository
      git:
        repo: "https://github.com/junegunn/fzf.git"
        dest: "~/.fzf"
        depth: 1

    - name: Run fzf install script
      command: ~/.fzf/install
      args:
        chdir: ~/.fzf
