- hosts: localhost
  gather_facts: true
  become: false
  pre_tasks:
    - name: Initial setup
      include_tasks: lifecycle/setup.yml
  vars:
    user: "{{ ansible_env.USER }}"
  tasks:
    - name: Include tasks
      include_tasks: "{{ item }}.yml"
      loop:
        - dotfiles/index
        - packages/install
        - packages/config
        - secrets/index
  post_tasks:
    - name: On finish
      include_tasks: lifecycle/finish.yml
# TODO:
# - set default input device
# - setup dev dir and pull the most improtant projects
# - install rust
# - install xidlehook
# - install and configure hyprpicker
# - install ts and ts lang server
